name: Headwayio Figma token translator - Test
description: 'test description'
author: Headwayio

on:
  push:
     branches:
       - main
jobs:
  generate-build-number-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      - run: npm install
      - run: npm run build
      - run: ls ${{ github.workspace }}
      - run: ls ${{ github.workspace }}/tokens
      - run: ls ${{ github.workspace }}/build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: automated change

